- hosts: all
  tasks:
          - name: Start Docker service
            service:
                    name: docker
                    state: started
                    enabled: yes

          - name: Install python 
            become: yes
            package:
                    name:
                            - python3
                            - python3-setuptools
                            - python3-pip
                    state: present

          - name: Install docker from pip
            become: yes 
            pip:
                    name: docker
